---
# tasks file for nginx
  - name: check nginx installed or not
    command: which nginx
    register: check_nginx

  - name: install nginx
    apt: name=nginx state=present update_cache=yes
    when: check_nginx.rc >= 1

  - name: configure nginx site
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ item.key }} mode=0644
    with_dict: "{{ sites }}"
    notify: restart nginx

  - name: get activated sites
    shell: ls -l /etc/nginx/sites-enabled
    register: activated_sites

  - name: de-activate default nginx site
    file: path=/etc/nginx/sites-enabled/{{item}} state=absent
    loop:
       - active.stdout_lines
    when: item not in sites
    notify: restart nginx
      
  - name: activate demo nginx site
    file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
    with_dict: "{{ sites }}"
    notify: restart nginx
  
  - name: ensure nginx started
    service: name=nginx state=started enabled=yes
