---
# tasks file for nginx
  - name: check nginx installed or not
    command: which nginx
    register: check_nginx
    tags: [ 'packages' ]

  - name: install nginx
    apt: name=nginx state=present update_cache=yes
    when: check_nginx.rc >= 1
    tags: [ 'packages' ]

  - name: configure nginx site
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ item.key }} mode=0644
    with_dict: "{{ sites }}"
    notify: restart nginx
    tags: [ 'configure' ]

  - name: get activated sites
    shell: ls -l /etc/nginx/sites-enabled
    register: activated_sites
    changed_when: "activated_sites.stdout_lines != sites.keys()"
    tags: [ 'configure' ]

  - debug: var=activated_sites.stdout_lines

  - debug: var=sites.keys()

  - name: de-activate default nginx site
    file: path=/etc/nginx/sites-enabled/{{item}} state=absent
    loop:
       - active.stdout_lines
    when: item not in sites
    notify: restart nginx
    tags: [ 'configure' ]
      
  - name: activate demo nginx site
    file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
    with_dict: "{{ sites }}"
    notify: restart nginx
    tags: [ 'configure' ]
  
  - name: ensure nginx started
    service: name=nginx state=started enabled=yes
    changed_when: false
    tags: [ 'service' ]